# Autogenerated wrapper script for XGBoost_jll for x86_64-linux-gnu-cxx11-cuda+12.0
export libxgboost, xgboost

using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("XGBoost")
JLLWrappers.@declare_library_product(libxgboost, "libxgboost.so")
JLLWrappers.@declare_executable_product(xgboost)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libxgboost,
        "lib/libxgboost.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        xgboost,
        "bin/xgboost",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
