# Autogenerated wrapper script for XGBoost_jll for x86_64-apple-darwin
export libxgboost

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("XGBoost")
JLLWrappers.@declare_library_product(libxgboost, "@rpath/libxgboost.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libxgboost,
        "lib/libxgboost.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
